version: '3.8'

services:
  nginx:
    image: nginx:1.23.3
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /home/root/FE/dist:/usr/share/nginx/html
      - /home/root/FE/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mge2116net

networks:
  mge2116net:
    external: true